package com.example.sunpengtao.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.sunpengtao.beans.Shuju;

import com.example.sunpengtao.db.ShujuDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig shujuDaoConfig;

    private final ShujuDao shujuDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        shujuDaoConfig = daoConfigMap.get(ShujuDao.class).clone();
        shujuDaoConfig.initIdentityScope(type);

        shujuDao = new ShujuDao(shujuDaoConfig, this);

        registerDao(Shuju.class, shujuDao);
    }
    
    public void clear() {
        shujuDaoConfig.clearIdentityScope();
    }

    public ShujuDao getShujuDao() {
        return shujuDao;
    }

}
